name: go-publish-log
on:
  push:
    branches:
      - log/*
jobs:
  npm-publish:
    name: go-publish-log
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check file changes
      uses: tj-actions/changed-files@v25
      id: check
      with:
        files: |
          ./log/go.mod
      outputs:
        version: ${{ steps.current.outputs.version }}
        type: ${{ steps.current.outputs.version }}
        commit: ${{ steps.current.outputs.version }}
      steps:
        - id: current
          run: echo "::set-output name=version::"`head -n 1 ./go.mod | sed "s/\/\///"`
    - name: Version update or file change detected
      if: steps.check.outputs.any_changed == "true"
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.18.0"
        cache: true

    - name: Test
      if: steps.check.outputs.any_changed == "true"
      run: make test-log

    - name: Create a GitHub release
      if: steps.check.outputs.any_changed == "true"
      uses: actions/create-release@v1
      with:
        tag_name: log/v${{ steps.check.outputs.version }}
        release_name: Release log/v${{ steps.check.outputs.version }}
        body: |
          Release: log/v${{ steps.check.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
